### ISSUE TITLE
ws연결 중인 클라와의 비실시간성 요청은 ws로 처리할까? http api로 처리할까?

### ISSUE THREAD

**Issue by jeeheaG** [Run-Us/Run-Us-server#11]
개발하다가 ws 엔드포인트 설계에 대해 다시한번 고민을 하게 되어서 
관련 구글링 후 생각을 다시해봤는데,
프로토 구현 시에는 크게 바뀌는 건 없지만 이전에 결정했던 것과 다른 결론이 나와서 ㅎㅎ.. 일단 얼른 공유드립니다..

- 고민 : ws연결 중인 클라와의 비실시간성 요청은 ws로 처리할까? http api로 처리할까?

- 이전 결론 : ws연결 중 http 요청을 추가로 하는만큼 부하가 추가로 듦. ws로 하자

- 새 결론 : api 로 뺄 수 있는 것은 api 로 빼는 것이 좋음
    - 이유 정리
    1. ws가 불필요 : web socket 의 용도는 실시간성 데이터를 받는 것이므로 실시간 통신이 필요하지 않는 api의 경우 ws를 쓸 이유가 없음
    2. 코드 재사용성과 모듈화, 유지보수성 : 나중에 그 api가 다른 곳에서 사용될 수도 있음. 따라서 기능의 성격에 맞게 설계하는 것이 더 적절함
    3. 부하만 본다면 웹소켓 통신 안하고 따로 HTTP api로 빼는 게 좀더 부하가 큼. 하지만 이게 엄청난 차이는 아님. 따라서 각 요청에 맞는 적합한 설계를 따르는 방향이 나음

어떻게 생각하시는지 이모지나 댓 남겨주시면 감사하겠습니다..!

**Comment by hughesgoon** [comment]
합리적인 의견이고 구분짓는것에 동의합니다.
그런데 혹시 지금 스펙상 분리해야할 요청은 어떤게 있을까요??

**Comment by jeeheaG** [comment]
프로토타입 구현중에는 더 분리할 사항은 없습니다!
여러명 러닝 구현에서는 다 분리시켜둬서 괜찮고 나중에 다른 기능 설계시에 고려하면 될 것 같아요.
