### ISSUE TITLE
[Development/Entity] - Running과 참여자 

### ISSUE THREAD

**Issue by ekgns33** [Run-Us/Run-Us-server#16]
### As Is
<img width="1011" alt="Screenshot 2024-09-25 at 3 50 10 PM" src="https://github.com/user-attachments/assets/0970adb5-98ed-483a-b0f8-560227f4312d">

- Running Entity는 사용자가 실시간 달리기를 만들었을때 (대기방 입장 / 혼자달리기) 시작 시에 생성됨.
- Participants는 Running 엔티티가 Set으로 저장하고 있는 참가한 사용자들의 id집합임.

### 고려할점
1. 일정거리 / 시간 이상 이동한 기록이 있어야 **유효한** 러닝으로 간주하는 요구사항이 있음.
2. **유저가 새로 들어올 때마다 참여한 사용자들의 정보**를 제공해야함.

### 문제 발생지점

**1. Participants는 값 객체가 맞나?**

- 현재 값객체로 사용자 id들을 들고있음. 참여한 사용자의 정보를 반환하기 위해서 두번의 쿼리가 실행됨.
```
select * from Running where public_id = "fdfd";

select (x,x) from User u where u.id in (1,2,3,4);

```
- 두번째 쿼리는 `in`을 사용하는 중. 아니면 직접 **jdbc로 네이티브 쿼리**?

**2. Running 엔티티가 의미하는 것을 명확히 해야한다.**

- RunningEntity를 실시간 서비스에서도 사용하고, 비실시간 (조회/생성)에서도 사용함.

- Running 엔티티가 들고있는 정보가 live 정보인지 Running Start이후에 fix되는 정보인지 정해야함.
  - 값객체로 만든이유는 실시간 달리기가 시작된 이후에는 추가 참가자가 존재하지 않기때문에 값객체로 만들었음. 

### 의견

1번은 더 이야기를 해봐요..

2번은 실시간 러닝이 시작되고 Participants를 메모리 저장소에서 읽어서 DB에 동기화하는게 어떨까요?
참여한 유저정보는 러닝세션 정보를 메모리저장소에 계속 들고있고 DB는 최대한 쿼리를 안하는 방향을 생각했어요.

**Comment by jeeheaG** [comment]
1. 전부터 값객체인지 고민되는 것들이 종종 생기는데, 정답이 있는지 모르겠어서 이렇게 고민이 되는 경우에 저희 안에서 가장 중요하게 생각하는 기준을 정하면 좋을 것 같아요. 
  i. 같은 속성을 가진 다른 객체로 대체할 수 있는가
  ii. 불변인가
  iii. 엔티티에 반드시 종속되는가
등등...
저는 Participants 같은 경우는 "같은 속성을 가진 다른 객체로 대체할 수 있"고, "엔티티에 반드시 종속"되어야 의미를 가지므로 VO 라고 판단하겠습니다.



3. Running 은 running start 후에는 fix되는 데이터가 맞는 것 같아요
그런데 다훈님이 말씀하신 대로 redis 에 넣는다면, 이후 정식 기능으로 구현할 때에는
러닝 생성 후 며칠 후에 실제로 러닝이 시작될 지 모르기 때문에 메모리에 좀 오래 들고 있게 되지 않을까요? 괜찮으려나요

**Comment by ekgns33** [comment]
> 3. Running 은 running start 후에는 fix되는 데이터가 맞는 것 같아요
>    그런데 다훈님이 말씀하신 대로 redis 에 넣는다면, 이후 정식 기능으로 구현할 때에는
>    러닝 생성 후 며칠 후에 실제로 러닝이 시작될 지 모르기 때문에 메모리에 좀 오래 들고 있게 되지 않을까요? 괜찮으려나요

<img width="960" alt="Screenshot 2024-09-25 at 6 39 49 PM" src="https://github.com/user-attachments/assets/598b36bf-4fc4-4fd3-9ef2-fef6fe2c5c16">

- 앗 이부분은 좀 더 설명을 드리자면 Running객체는 "예정된 달리기" or "바로 시작하는 달리기"를 생성하면 바로 DB에 저장하고,
참여자를 확정하는 부분만 메모리에 올려놨다가 DB에 lazy하게 동기화하는 것을 이야기한거였습니다!


따라서 live 대기방을 만들면 참여자 정보들이 메모리에 올라가겠죠?
