### ISSUE TITLE
What we use: OIDC or OAuth

### ISSUE THREAD

**Issue by hughesgoon** [Run-Us/Run-Us-server#24]
오랜만에 돌아온 뻘소리 이슈입니다.
중요한건 아니고요. 이번에 기반을 잡는 단계인만큼 그냥 한번 정리해도 좋지않을까 해서 열어봅니다.

사실 요즘 대다수의 서비스는 OAuth AccessToken을 OIDC의 개념을 혼용하고 있는 상황인데요.
저희 서비스에서 발급되는 JWT는 어떤걸까 한번 여쭤보려 합니다.
*(유저 인증서 개념인거죠..? 지금은 인증개념으로 짜놨습니다. 👉👈)*

---

1. 개념적으로 OIDC는 사용자가 누구인지(subject) 인증만 다룹니다.
2. OAuth는 사용자가 어떤 리소스(audience)에 어느수준의 권한(scope)이 있는지 상세한 인가 범위를 담습니다.
3. 저희 JWT 로그인 토큰에는 무엇을 담아서 줄까유..?

**Comment by jeeheaG** [comment]
옹
서비스적으로 유저 권한을 나눌 일이 딱히 없는 것 같아서 OIDC 로 가도 괜찮을 것 같다는 생각이 듭니다

**Comment by ekgns33** [comment]
@hughesgoon 정해진 내용 있을까요?

**Comment by hughesgoon** [comment]
아마 그냥 유저의 public_id만 담은 jwt 토큰을 내려줄 것 같아서 OIDC와 유사하게 동작하지 않을지 싶습니당
