### ISSUE TITLE
[Runnning/Querying-User] - 불필요하게 유저정보를 계속 조회하는 로직 수정

### ISSUE THREAD

**Issue by ekgns33** [Run-Us/Run-Us-server#27]
### AS IS

- #17 
PR이전에는 **유저정보를 헤더에 저장하지 않아** 메세지에서 id를 읽어 유저정보가 필요할때마다 
데이터베이스에 조회했음.

- **현재는 CONNECT 이후 인증된 유저정보가 헤더에 존재**하기 때문에 추가적인 쿼리없이 유저정보를 사용할 수 있음. 

### TO BE

- 기존 코드의 불필요한 유저 쿼리 삭제 및 헤더정보를 사용하도록 수정

**Comment by ekgns33** [comment]
@jeeheaG 혹시 해당 이슈 작업해주실 수 있을까요?

**Comment by jeeheaG** [comment]
넵 최대한 보이는 대로 찾아서 바꿔놓겠습니다~
