### ISSUE TITLE
[Running/Passcode] - 입장시 Passcode? Public Id?

### ISSUE THREAD

**Issue by ekgns33** [Run-Us/Run-Us-server#30]
### AS-IS

- PASSCODE가 현재는 거의 pulbic key처럼 사용된다. 어떻게하면 public key만 공개할 수 있을까?

- PASSCODE를 키로 사용하면 4자리 알파벳포함 + 9개 숫자인데 보안에 위험하지 않은가? 

경우의 수가 36^4  = 1679616가지 (물론 계정이 있어야 요청을 날릴 수 있다.)

**Comment by ekgns33** [comment]
시도해본 것들
1. 입장하고 /user/queue/log 를 구독한다. 그리고 CONNECT를 한번 더 쏘면 방번호를 준다.
2. runningId를 클라이언트에서 아예 사용하지 않게한다. 그냥 connect할때 passcode가 키 역할을한다.
<< 프로토타입 + v.0.1.0에서는 러닝을 어딘가에 등록하고 조회하는 기능이 없음. 따라서 러닝 id 노출이 안됨. 
<< 친구들끼리 갑작스럽게하는 러닝들 (방만들기로 바로 진행되는 러닝들)은 그냥 passcode로 입장하게 한다. 어차피 connection하나가 session하나이기때문에 논리적으로는 괜찮다. but 보안 괜찮나?

**Comment by jeeheaG** [comment]
현재님이 올려주신 PASSCODE 도입 배경을 다시 보고 생각해봤는데
유저 편의성을 챙기는 의도만 살릴 수 있도록 
첫 요청에서만 사용하고, 그 후 러닝에 해당하는 public key 를 줘서
나머지 통신에서는 모두 public key 를 사용하는 게 통일성 면에서 저도 좋을 것 같습니다. 동의합니다
