### ISSUE TITLE
[DB ERD] 개인기록 테이블, 러닝기록 테이블 ERD 수정

### ISSUE THREAD

**Issue by ekgns33** [Run-Us/Run-Us-server#32]
## 1️⃣  사용자 개인 데이터 

1. 사용자가 앱을 사용하면서 달린 누적거리
2. 사용자가 앱을 사용하면서 달린 누적 시간
3. 사용자가 앱에서 달린 최장 거리 기록
4. 사용자가 앱에서 달린 최장 시간 기록

- 모두 추가해야함.

## 2️⃣  개인 달리기 기록

1. 총 달린 거리
2. 총 달린 시간
3. 평균 페이스

- 추가해야함.

## 3️⃣   단체 달리기 기록 

AS-IS
단체 달리기에서 모든 사용자의 기록을 통계로 저장하는 `running_records` 라는 테이블 존재함.
이 테이블에는 달린 인원수, 달리기를 종료한 사람, 달리기의 시작과 끝 시간 정보가 있음.

TO-BE
현재 요구사항에서 전체 달리기가 끝나면 필요한 정보
1. 같이 달린 사람들
2. 같이 달린 사람들의 이동거리, 평균 페이스, 달린 시간

- 컨텐츠가 추가되면 모든 달린사람들의 데이터로 통계도 여러 방식으로 보여주고 할 것 같습니다.
- 하지만 현재 상황에서는 기존 사용자들이 저장하는 `PersonalRecords`들의 일부 정보만 필요한 것 같습니다.

**Comment by hughesgoon** [comment]
# 📢 ERD 업데이트

[⛓️ 링크](https://dbdocs.io/hughesgoon/RunUS?view=relationships)

## 크루 관련 테이블 추가
- crews: 러닝크루
- crew_memberships: 크루-유저 매핑
- crew_join_requests: 크루 가입 신청 로그

## 프로필 기록 추가
- total_time, total_distance: 총 달린 시간과 거리
- longest_time, longest_distance: 최고 기록

## 러닝세션 기록 관련 aggregate column 추가
- running_records.avg_pace: 러닝세션 전체 완주자의 평균 페이스
- personal_records.avg_page: 러닝세션에서 개인별 평균 페이스
- personal_records.duration: 러닝세션에서 개인별 달린 시간
- personal_records.distance: 러닝세션에서 개인별 달린 거리

## 기타 자잘한 수정
- FK 방향이 이상했던 제약조건 2개 정도 수정했습니다.
- 미쿡식 영어로 Enum 수정했습니다.
- 닉네임 8글자로 변경했습니다.
- dbdocs에는 안나오는데, 닉네임 관련 constraint 걸었습니다.
  ```
  CONSTRAINT `check_nickname_length` CHECK (CHAR_LENGTH(`nickname`) BETWEEN 2 AND 8)
  CONSTRAINT `check_nickname_chars` CHECK (`nickname` REGEXP '^[가-힣a-zA-Z0-9]+$')
  ```

## TODO
- JPA Validation(...)

**Comment by ekgns33** [comment]
고생하셨숨돠~!!

**Comment by ekgns33** [comment]
@hughesgoon `PersonalRecord` 테이블에 RunningType enum (SINGLE, GROUP)이 빠져있는것 같습니다! 그리고 RunningStatus의 경우 `COMPLETED`, `ABANDONED`, `ERROR` 정도인데 PersonalRecord에서 이 상태를 들고있어야할까 고민이 되네요. 혼자달리기의 경우 달리기의 결과가 항상 완료가됩니다

**Comment by hughesgoon** [comment]
> @hughesgoon `PersonalRecord` 테이블에 RunningType enum (SINGLE, GROUP)이 빠져있는것 같습니다! 그리고 RunningStatus의 경우 `COMPLETED`, `ABANDONED`, `ERROR` 정도인데 PersonalRecord에서 이 상태를 들고있어야할까 고민이 되네요. 혼자달리기의 경우 달리기의 결과가 항상 완료가됩니다

이것도 계속 이어져온 싱글은 별도인가, 1명인 그룹인가와 연결될 수 있어 조심스러운데요.

사실 레코드 입장에서는 싱글인지 그룹인지 알 이유가 없을 것 같습니다. 만약 구분이 필요하다면 FK로 연결된 runnings에서 구분해야 하지 않을지 싶습니다.
개념적으로 runnings가 있어야 record가 존재하는거니까요.

ENUM은 저희 데이터의 신뢰성과 안정성이 어느 수준까지 보장될지 모르겠어서 인증씰 느낌으로 넣었는데요.
사실 그룹런의 abandoned 때문에 생긴거에 가깝긴한데, error에 대한 처리가 DB 밖 비즈니스 로직에서 관리해줄 방안이 있으면 boolean으로 바꿔도 될거같긴 하네요.

**Comment by ekgns33** [comment]
@hughesgoon 확실히 Running이 자신이 어떤 타입의 러닝인지 상태를 저장하는게 맞아보이네요! 에러에 대한 처리관해서는 제가 이해하기로는 클라이언트에서 달리기 데이터를 들고있다가 
1. 그 데이터를 버리거나 
2. 서버에 전송하거나
의 흐름이었던것 같습니다. 그래서 서버입장에서는 그냥 데이터를 저장하기만하고 그 달리기가 자격미달인지만 확인하면 되지않을까요?

**Comment by hughesgoon** [comment]
> @hughesgoon 확실히 Running이 자신이 어떤 타입의 러닝인지 상태를 저장하는게 맞아보이네요! 
> 에러에 대한 처리관해서는 제가 이해하기로는 클라이언트에서 달리기 데이터를 들고있다가 
> 1. 그 데이터를 버리거나 
> 2. 서버에 전송하거나
> 의 흐름이었던것 같습니다. 그래서 서버입장에서는 그냥 데이터를 저장하기만하고 그 달리기가 자격미달인지만 확인하면 되지않을까요?

당시 상황을 떠올리면 아마 실제로 데이터가 오건 안오건 record는 존재해야 했습니다.
그래서 이게 추후에 데이터 업로드 시점의 문제였는지, 호출시점 문제였는지 구분하려는 용도였네요.
혹시라도 클라에 값이 남았다면, 재업로드 요청을 할 수도 있고요.

아니면 둘다 에러니까 데이터가 비정합이라면 그냥 record를 날리거나 data null 허용해도 되겠네요. 원하시는걸로 하겠습니다.
