### ISSUE TITLE
FK 연관관계에서의 API 설계

### ISSUE THREAD

**Issue by hughesgoon** [Run-Us/Run-Us-server#35]
RESTful 하지는 않지만 나름대로 최대한 엔드포인트 설계에 반영하려 노력중인데요.
FK 연관관계에서 설계방향을 조금 통일하고자 이슈올립니다.
(어제 일정이 너무 꼬여서 죄송합니다..)

예를들면, 크루-러닝세션을 상황으로 가정할게요. (아예 종속적인 리소스는 사실 고민할 여지가 없고) 크루의 러닝세션을 조회하는 그런 레벨이 동등한 API를 생각해볼게요.
"크루와 관련된 러닝세션" 이라면 `크루`라는 폴더에서 `특정 크루`를 들어가서 `러닝세션`이라는 리소스를 본다 생각할 수도 있고,
"러닝세션인데 크루나 유저에 따라 조회"라면 `러닝세션`이라는 폴더에서 `유저`혹은 `크루` 폴더에 들어가 `러닝세션`을 가져오는 것으로 생각할 수 있겠죠?

- 러닝세션을 주 리소스로 두고 크루나 유저를 파라미터로 처리(GET /runnings?crew={}&user={})
- 비즈니스 로직에 따라 크루 혹은 세션이 주도적으로 처리(GET /crews/{id}/runnings **or** GET /runnings?crew={})
- 사용사례에 따라 양측 도메인에서 각각 엔드포인트 제공(GET /crews/{id}/runnings **and** GET /runnings?crew={})

위 3가지 방법 모두 상황에 따라 취사선택하는 영역이라 평소 이야기를 듣고싶습니다.
저는 개인적으로 **기획의 주요 비즈니스 도메인**에 책임을 몰아서 복잡성을 줄이는 것을 선호하긴 하는데, 요청하는 입장에서는 양측 엔드포인트가 모두 있을때 더 직관적일수도 있고,,,
아무튼 유저, 러닝세션, 크루, 레코드 이런거 어떻게 하면될지 의견을 구합니다..

**Comment by ekgns33** [comment]
정말 논란거리인 주제군요 ㅋㅋㅋ

RESTful을 엄격히 지켜야한다면, 하나의 리소스를 표현하는 방법은 한가지여야겠죠.. 따라서 여러개의 엔드포인트로 동일한 리소스를 가리키는게
엄격한 REST를 지키는 것은 아닌 것 같습니다. 

- 이전에 읽었던 레딧에서 이런 주장들이 있었습니다.
  - 읽기 전용이라면 여러 엔드포인트가 있는 것은 괜찮다. 하지만 PUT, PATCH, POST등의 상태를 변경하는 요청으로 리소스에 수정이 일어나고나서 다른 모든 읽기 요청들이 캐시를 읽는게 아니라 수정된 원본을 봐야한다면 하나의 엔드포인트만 둬야한다.
  - 무조건 하나만 해야한다. REST는 리소스를 표현하는거지 비즈니스를 표현하는게 아니다..
  
뭐 이런 것들이 있었던거로 기억하네요.

저는 보통 도메인의 중심이되는게 뭔지 보는 것 같습니다. 가령 달리기라는 도메인이 크루 도메인에 속하나?같은 1번을 선호하는것같습니다.

**Comment by hughesgoon** [comment]
좋은 답변 감사함다!
주요 도메인이 주도권을 가지게 된다면 {러닝(+레코드??), 유저, 크루} 각각 충돌 안나도록 분배해보고, 이거에 맞춰서 각 도메인 조회단에서는 FK관계 쿼리 파라미터를 조금 조정하긴 해야겠네요.

이거 적다보니 떠오른 후속질문? 잡생각?인데, 그렇다면 `크루의 정보를 불러온다` 라는 `GET /crews/{crewPublicId}`에서는 크루가 뛰었던 정보 그런건 빼고 순수한 crew와 관련된 정보를 가져오는게 맞는거겠죠?!

**Comment by jeeheaG** [comment]
저도 RESTful 하게 짠다면 
엔드포인트는 리소스 간의 관계를 알맞게 표현해야 한다고 생각합니다.
특별히 이유가 있는 게 아니라면 상하관계가 뒤집어지는 경우는 피하도록 설계하구요
슬래시는 리소스 간 종속관계를 표현하는 거라고 들어서 저도 1번에 한표 던지겠습니다~~
