### ISSUE TITLE
[Time Scale] - 밀리초로 저장했을때 문제가 없을지

### ISSUE THREAD

**Issue by ekgns33** [Run-Us/Run-Us-server#46]
밀리초 = 0.001초로 계산하면 순수 달리기시간으로 24시간을 달리면  86,400,000밀리초입니다.

생각보다 숫자가 많이 커져서 당황잼이네요.
<img width="840" alt="Screenshot 2024-11-04 at 1 10 15 PM" src="https://github.com/user-attachments/assets/2e5867fa-c5cd-41ec-97ba-7a7f77cc482c">

- 단일 달리기에 대해서 저같이 680시간 켜놓는 사람이 있으면 터지는 수치네요. 현재 저희는 Integer을 사용합니다.
- 누적 달리기로 생각하면 확실히 변경이 필요합니다.

제안 
단일 달리기는 **밀리초 단위를 유지**하고, **자료형을 Long**등으로 바꾼다. 누적달리기는 스케일을 초/분 단위로 바꾼다.

**Comment by hughesgoon** [comment]
확실히 변경은 필요하네요. 데이터랑 싱크 맞추기 편해서 밀리초 했던건데, 이것부터 고민해야겠어요.

단거리 전문선수가 아니고, 러닝 특성상 길게 뛰니 초단위로 기록을 바꿔도 될 것 같습니다.
그럼 Integer로 대략 68년은 감당할 수 있게돼요.

밀리초를 한다면 Long이 필수적인데, 러닝기록에서 밀리초가 필요할지 🤔

**Comment by jeeheaG** [comment]
사용자 관점에서도 밀리초까지 굳이 원하진 않을 것 같아요
초단위로 바꾸고 싱크를 위한 데이터가 필요한 상황이 오면 카운트 데이터를 활용하는 방법을 그때 다시 생각해보는 게 좋지 않을까요?

**Comment by ekgns33** [comment]
초 단위로 변경하겠습니다
