### ISSUE TITLE
[Bug] : 로그인 요청시 에러

### ISSUE THREAD

**Issue by ekgns33** [Run-Us/Run-Us-server#48]
[로그인 요청 시 에러]
![Screenshot 2024-11-04 at 2 52 48 PM](https://github.com/user-attachments/assets/62f6fa2e-b1a8-4d93-b9b8-32c9b5dd7aac)

    
 ```   
    "message": "Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.run_us.server.domains.user.controller.model.response.AuthResponse> com.run_us.server.domains.user.controller.AuthController.login(com.run_us.server.domains.user.controller.model.request.AuthLoginRequest): [Field error in object 'authLoginRequest' on field 'oidcToken': rejected value [null]; codes [NotBlank.authLoginRequest.oidcToken,NotBlank.oidcToken,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [authLoginRequest.oidcToken,oidcToken]; arguments []; default message [oidcToken]]; default message [must not be blank]] ",
```

**Comment by ekgns33** [comment]
![Screenshot 2024-11-04 at 3 03 25 PM](https://github.com/user-attachments/assets/0111c258-1504-4470-bda1-8cbeef071081)

언더바추가하니 되네요

**Comment by ekgns33** [comment]
![Screenshot 2024-11-04 at 3 07 24 PM](https://github.com/user-attachments/assets/cb4a8a92-8ddb-485c-a1cb-eb897c244189)

아..? 스네이크로 설정을 해놔서 그렇군요... @hughesgoon @jeeheaG 기억이 안나는데 우리 스네이크 하기로 했나요?

**Comment by hughesgoon** [comment]
노션 스펙이나 리뷰때 확인거쳐졌길래 스리슬쩍 넘어가진건데요.
글게요,,, 카멜로 할까요..?

일단 표준은 없습니다.
- 통상 자바, js 진영은 카멜 / 파이썬, php는 스네이크를 썼고
- 구글은 카멜 / 트위터, 메타는 스네이크 / AWS는 스까서 쓰긴합니다.

정한적이 없어서 원하는대로~,,

**Comment by jeeheaG** [comment]
제 사견으로는 치기 쉬운 건 카멜 / 읽기 쉬운 건 스네이크.
근데 구글이랑 MS 에서 카멜 권장한다고 하네여
카멜할까요? 저도 둘다 좋아요
