### ISSUE TITLE
[Requirements & Policy] - 각종 요구사항과 정책 정립

### ISSUE THREAD

**Issue by hughesgoon** [Run-Us/Run-Us-server#50]
## 개요

- 협의가 가능한 요구사항에 대한 논의(백엔드 영역/각자 최대 1개의 코멘트)
- 그외 모든 영역에 대한 결정권 위임 제안(전체 영역/전체팀원 중 1~2인)

## 배경

계속 돌고 돌고 돌아온 이슈입니다.
지금 **당장의 기능을 만드는 것**과 **스펙 정리**가 상호 데드락을 발생시켜 진행이 매우 더뎌진 것 같습니다.

사실 PM 모두 요구사항도 꼼꼼히 적어주었고, 개발팀도 각자 PR을 올리고 잘하고 있으나 이번 스프린트에 보이지 않는 데드락이 있어보입니다. 왜일까요...?(약간의 반성을 곁들여봅니다..)
협의로는 해결이 어려운 수준인 것 같고, 어느정도 누군가에게 권한을 위임해야하나 싶습니다.

제안 배경은 이렇습니다.
- 요구사항이 결정되고, API 스펙이 잡힌 이후, **로직의 구현과 최적화**는 개발의 영역이지만
- **정책 자체에 영향이 가는 모든 행위**는 개발자가 결정해선 안되고, RunUS **팀원으로서 제안**으로 그쳐야 한다 생각합니다.

## 러닝 관련 의사결정

> 1. 코멘트로 진행 가능한 2. 백엔드 영역의 3. 급한 이슈입니다.

MVP 0.1과 이후의 최대 차이점은 러닝입니다.
- 최초: 싱글런과 그룹런 모두 `러닝`이며, 이에 종속적인 `레코드`, `참가자`가 존재한다는 요구사항이었습니다.
- 변경: 싱글런은 로직과 저장 형식이 **그룹런과 분리**됩니다.

제안을 모아 정리해보면 좋겠습니다.
- **제안1**: 도메인 메인 주체를 `레코드`로 변경. `러닝`의 개념을 `그룹런`으로 변경.
- **제안2**: `러닝`이라는 개념을 유지하고, nullable 칼럼을 null로 두는 방법.
- 기타 제안을 각자 1개씩 올려보고, 최종적으로 엔티티를 고정해보면 어떨까요?

## 결정권 위임에 관한 안건

api 스펙은 각자 열심히 만들었으나, 아직도 요구사항과도 코드와도 백엔드 3인끼리도 혼선이 많습니다.
또, 클라이언트가 어떤 것이 필요한지, 어떤게 오프라인 캐싱이 되는지, 어떤게 api 통신일지 정해지지 않은 게 많습니다.

PM 혹은 개발팀(클라, 백엔드) 어딘가에서 주도권을 가지고 가는게 좋지 않을지..
더욱이 해당 주도권을 책임지고, 다른 모두가 이에 따르는 방향으로 속도를 높여보면 어떨지 싶습니다.
이것도 백엔드 팀원 1로서 단순 제안입니다.

**Comment by hughesgoon** [comment]
## 요청사항

아래 내용중 편하신걸로,,, 자유로운 의견 부탁드립니다.

1. 본 이슈 자체에 대한 의견
2. 러닝 관련 정책에 대한 의견
3. 주고받을 정보 최종결정권에 관한 의견(협의체 or 책임제 or 기타)

**Comment by ekgns33** [comment]
>제안1: 도메인 메인 주체를 레코드로 변경. 러닝의 개념을 그룹런으로 변경.
제안2: 러닝이라는 개념을 유지하고, nullable 칼럼을 null로 두는 방법.
기타 제안을 각자 1개씩 올려보고, 최종적으로 엔티티를 고정해보면 어떨까요?

요 제안에 대해서는 기존의 `Running`이 다수 사용자에서 사용되는 달리기 (이하 멀티런)로 이전하고, 기록이라는 엔티티를 두 러닝 모두 사용하게 하는게 좋아보입니다. 결국 러닝에 대한 공지, 신청, 참가 기능이 포함되는 멀티런은 공지와 같은 데이터가 존재하겠죠.

나머지 정책적 이슈에 대해서는 저도 어느정도 동감합니다. 그런데 레포지토리 이슈에서 다루기엔 뭔가 회고 + Discussion 느낌이 나는것 같아서 노션으로 이동하는게 어떨지요?

**Comment by jeeheaG** [comment]
[1,3번 안건에 대한 의견] 
개발자로서의 의견은 팀원으로의 의견으로 그쳐야한다에 큰 동의를 합니다.
사실 이건 제 스타일이기도 한데요, 진행에서 뭔가 논의가 반복되고 선택의 문제인 상황들이 오면 그냥 누군가 한명, 또는 규칙 하나를 절대적으로 정해두고 밀고 나가는 게 왠만한 논의보다 좋다고 생각합니다. 프로젝트에서 마주치는 문제들은 대부분 정답이 없는 경우들이라 긴 고민보다는 일관성을 유지해서 팀 혼란을 줄이고 속도를 내는 게 이득일 때가 많았어요. 다만 이 때 밀고나간 의견을 뒷받침하는 근거&이유를 놓치지 않아야 하고, 기록이 여기에 기여한다고 생각합니다.
또 사견을 보태자면, 어떻게 들릴지 조심스럽지만... 뭔가 결정할 때 결정권자나 발제자가 반쯤 결정해와서 이유를 공유하고 대안을 고민하는 게 효율적으로 진행된다고 생각합니다.
-> 결론 : 반복되는 혼란을 줄이기 위해 룰&권력자를 정해서 이유와 함께 밀고나가도록 해주는 게 어떨지요.

[2에 대한 의견]
그동안 계속 애매한 감이 있었는데 레코드를 메인으로 잡으면 깔끔해질 것 같아보이네요(막상 설계 고쳐보면 또 걸리는 부분이생길 수 있지만..)
레코드를 메인으로 잡고 다시한번 전체적인 설계를 검토해보는 것도 좋을 것 같습니다.

의견 올려주셔서 감사합니다! 아무쪼록 잘 나아갈 수 있길,,

**Comment by hughesgoon** [comment]
어제 회의로 정리된 부분이 있어 여기에도 적고 이슈 닫겠습니다.
## 러닝 엔티티
메인 엔티티를 레코드로 하며, 그룹런과 이외 프리뷰 등은 기획 요구사항을 보며 결정
## 태스크 책임자
- 태스크 관리책임과 권한은 기본적으로 PM겸 백엔드인 문다훈에게 일임.
  - (토의가 이뤄진 상황이라면 이슈, 스레드 모두 최종 결정은 다훈)
- 단, 최종 의견 이후 **24시간동안 피드백이 없는 경우, 발제자가 최종 정리 및 확정**.
